version: '2'

services:

    tudo:
      image: node
      ports:
        - 80:80
      volumes:
        - ${PWD}:/root/tudo
      command: bash -c "cd /root/tudo && npm i && npm run dev"
      tty: true

    tudo-mongo:
      image: mongo:latest

networks:
  default: