### ユーザ登録
POST http://localhost:80/api/signup
content-type: application/json

{
    "displayName" : "aa",
    "username" : "user115",
    "password" : "pass"
}

### ログイン
POST http://localhost:80/api/signin
content-type: application/json

{
    "username": "user115",
    "password": "pass"
}

### ログアウト
POST http://localhost:80/api/signout

### ユーザ情報の取得
GET http://localhost:80/api/user

### ログイン中ユーザのタスク取得
GET http://localhost:80/api/tasks

### ログイン中ユーザのタスクの追加
POST http://localhost:80/api/tasks/create
content-type: application/json

{
  "title": "タスク",
  "icon": "",
  "description": "やること一覧",
  "dueTime": "2019-09-20 21:11:00",
  "member" : ["user115"]
}

### タスク更新（チェックの例）
POST http://localhost:80/api/tasks/update/10
content-type: application/json

{
    "status" : true
}

### 他人のタスク閲覧
GET http://localhost:80/api/users/user114/tasks
content-type: application/json


### チーム作成
POST http://localhost:80/api/groups/create
content-type: application/json

{
  "groupname": "project-X",
  "displayname": "プロジェクトX",
  "member" : ["user115"]
}

### グループタスクの追加
POST http://localhost:80/api/tasks/create
content-type: application/json

{
  "title": "グループのタスク",
  "icon": "",
  "description": "やってね",
  "dueTime": "2019-09-20 21:11:00",
  "groupname": "project-X",
  "member" : ["user115"]
}

### グループタスクの取得
GET http://localhost:80/api/groups/tasks/project-x
content-type: application/json





### Show Task Intent
POST http://localhost:80/api/fullfillment/ShowTaskIntent
content-type : application/json

{
  "name" : "Show Task Intent",
  "param" : {
    "value" : ""
  }
}

###Num Specified Intent
POST http://localhost:80/api/fullfillment/NumSpecifiedIntent
Content-Type: application/json

{
  "name" : "Num Specified Intent",
  "param" : {
    "value" : 1
  }
}

### Show Tomorrow Task Intent
POST http://localhost:80/api/fullfillment/ShowTomorrowTaskIntent
Content-Type: application/json

{
  "name" : "Show Tomorrow Task Intent",
  "param" : {
    "value" : "2019-12-14T12:00:00+09:00"
  }
}

### TaskCheck Intent
POST http://localhost:80/api/fullfillment/TaskCheckIntent
Content-Type: application/json

{
  "name" : "TaskCheck Intent",
  "param" : {
    "value" : "おでかけ"
  }
}

